### ISSUE TITLE
Game crashes when last shot removed

### ISSUE THREAD

**Issue by crookm** [crookm/Asteroid#24]
When some shots are fired and they all travel off-screen, the game crashes.

**Comment by crookm** [comment]
Error as follows:
```
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at Asteroid.manageShots(Asteroid.java:348)
	at Asteroid.updateGame(Asteroid.java:435)
	at Asteroid$AnimationThread.run(Asteroid.java:498)
```

**Comment by crookm** [comment]
Added a break at line 345 in 81ef769f56.
Thanks to @blackbrad
